refresh_rate: 2.0
max_alerts: 10
max_nodes_display: 10
max_topics_display: 15

collection_intervals:
  system_metrics: 2.0
  network_ping: 5.0
  ros_discovery: 10.0      # Poll every 10 seconds
  ros_callbacks: 0.01      # Process messages every 10ms
  hz_collection_duration: 3.0  # Collect Hz data for 3 seconds per poll

thresholds:
  cpu_warn: 70.0
  cpu_error: 90.0
  memory_warn: 80.0
  memory_error: 95.0
  disk_warn: 85.0
  disk_error: 95.0
  temperature_warn: 70.0
  temperature_error: 85.0
  network_latency_warn: 100
  network_latency_error: 500

ros:
  critical_topics:
    - name: "/cmd_vel"
      target_frequency: 10.0
    - name: "/odom"
      target_frequency: 30.0
  node_patterns:
    navigation:
      - "nav2*"
      - "*navigation*"

display:
  show_colors: true
  show_progress_bars: true
  time_format: "%H:%M:%S"